-- Power BI DAX measures for Customer Churn Dashboard

Total Customers = DISTINCTCOUNT(customer_churn_processed[customerid])

Churned Customers = CALCULATE([Total Customers], customer_churn_processed[churn] = 1)

Churn Rate = DIVIDE([Churned Customers], [Total Customers])

Revenue at Risk = SUM(customer_churn_processed[revenue_at_risk])

Average CLV = AVERAGE(customer_churn_processed[customer_lifetime_value])

High-Risk Customers =
CALCULATE([Total Customers], customer_churn_processed[high_risk_customer_flag] = 1)

Retention Opportunity =
CALCULATE(
    SUM(customer_churn_processed[annual_value_proxy]),
    customer_churn_processed[high_risk_customer_flag] = 1
)
